## Setup
title:               Diffraction Microstructure Imaging
tagline:             'Crystalline Materials in 3-D'
description:         'Resources to promote and further develop <i>Diffraction Microstructure Imaging</i>'
url:                 https://dmi-3d.github.io/
#baseurl:             'https://github.com/dmi-3D/dmi-3D.github.io'
paginate:            5
permalink:           pretty
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics:
show_downloads: false
# theme: jekyll-theme-slate


gems:
  - jekyll-mentions
